#!/bin/bash

# echo "upstart_test service started"
# while true
# do
#     echo "upstart_test running ..."
#     # sleep for 15min
#     sleep 2    
# done
#

if [ -e "/etc/init/watchdog.conf" ]; then
    invoke-rc.d watchdog start || exit $?
fi

update-rc.d -f watchdog remove >/dev/null
update-rc.d watchdog defaults 25 >/dev/null